import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Add this import
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'screens/role_selection_page.dart';

void main() async {
  // 1. Ensures Flutter is ready to talk to the native platform
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Starts the connection to your Firebase project
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: RoleSelectionPage(),
    );
  }
}
